### ISSUE TITLE
Wallet does not shutdown daemon

### ISSUE THREAD

**Issue by 2a5A1Ghu1** [VitaeTeam/vitae-gui-electron-wallet#17]
When quitting the wallet, the background daemon does not shutdown properly intermittently on macOS 10.15 and has to be killed via the terminal.

**Comment by devstar11** [comment]
Did you only click 'x'? or Did you try to click Menu/Quit?
In mac, it's possible to close windows using 'x' and this doesn't mean completely ended so in most electron wallets, to exit the app in mac, need to close by menu or right-click of icon and close.

**Comment by sarawut11** [comment]
The issue was resolved.

**Comment by 2a5A1Ghu1** [comment]
fixed with commit https://github.com/VitaeTeam/vitae-gui-electron-wallet/commit/4422353dcfcf2e6664bb881665f1125e9e412613
